version: '3'

services:
  nodejs-app:
    image: freedafrancis/nodejs-app:latest
    container_name: nodejs-app
    networks:
      - njnet
    restart: always
    ports:
      - "80:3000"
networks:
  njnet:
